### ISSUE TITLE
Can't sign in self-hosted app

### ISSUE THREAD

**Issue by all-mute** [Meldiron/authui#3]
AppwriteException: The requested route was not found. Please refer to the API docs and try again.
    at Client.<anonymous> (file:///C:/Users/Eva-02/VScode_projects/_startups/flexin/node_modules/appwrite/dist/esm/sdk.js:391:27)
    at Generator.next (<anonymous>)
    at fulfilled (file:///C:/Users/Eva-02/VScode_projects/_startups/flexin/node_modules/appwrite/dist/esm/sdk.js:22:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 404,
  type: 'general_route_not_found',
  response: {
    message: 'The requested route was not found. Please refer to the API docs and try again.',
    code: 404,
    type: 'general_route_not_found',
    version: '0.13.5'
  }
}

I did everything following setup instructions

**Comment by all-mute** [comment]
changed `'customDomain'` to `'domain'` in routes/+page.ts , it helped.
